"""Starting content: 20 lessons x 10 vocabulary items, as plain data.

No behavior lives here — `database.py` reads this once, on first run, when
the `lessons` table is empty. This content is backend-authored (the specs
define the shape/quantity, not the actual words) and can be extended later
through the Admin endpoints without touching this module.
"""

LESSONS = [
    {
        "title": "Greetings",
        "vocabulary": [
            {"hebrew": "שלום", "meaning": "hello"},
            {"hebrew": "להתראות", "meaning": "goodbye"},
            {"hebrew": "בוקר טוב", "meaning": "good morning"},
            {"hebrew": "ערב טוב", "meaning": "good evening"},
            {"hebrew": "לילה טוב", "meaning": "good night"},
            {"hebrew": "תודה", "meaning": "thank you"},
            {"hebrew": "בבקשה", "meaning": "please"},
            {"hebrew": "סליחה", "meaning": "excuse me"},
            {"hebrew": "נעים מאוד", "meaning": "nice to meet you"},
            {"hebrew": "מה נשמע", "meaning": "what's up"},
        ],
    },
    {
        "title": "Numbers 1-10",
        "vocabulary": [
            {"hebrew": "אחת", "meaning": "one"},
            {"hebrew": "שתיים", "meaning": "two"},
            {"hebrew": "שלוש", "meaning": "three"},
            {"hebrew": "ארבע", "meaning": "four"},
            {"hebrew": "חמש", "meaning": "five"},
            {"hebrew": "שש", "meaning": "six"},
            {"hebrew": "שבע", "meaning": "seven"},
            {"hebrew": "שמונה", "meaning": "eight"},
            {"hebrew": "תשע", "meaning": "nine"},
            {"hebrew": "עשר", "meaning": "ten"},
        ],
    },
    {
        "title": "Colors",
        "vocabulary": [
            {"hebrew": "אדום", "meaning": "red"},
            {"hebrew": "כחול", "meaning": "blue"},
            {"hebrew": "ירוק", "meaning": "green"},
            {"hebrew": "צהוב", "meaning": "yellow"},
            {"hebrew": "שחור", "meaning": "black"},
            {"hebrew": "לבן", "meaning": "white"},
            {"hebrew": "כתום", "meaning": "orange"},
            {"hebrew": "סגול", "meaning": "purple"},
            {"hebrew": "ורוד", "meaning": "pink"},
            {"hebrew": "חום", "meaning": "brown"},
        ],
    },
    {
        "title": "Family",
        "vocabulary": [
            {"hebrew": "אמא", "meaning": "mother"},
            {"hebrew": "אבא", "meaning": "father"},
            {"hebrew": "אח", "meaning": "brother"},
            {"hebrew": "אחות", "meaning": "sister"},
            {"hebrew": "סבא", "meaning": "grandfather"},
            {"hebrew": "סבתא", "meaning": "grandmother"},
            {"hebrew": "דוד", "meaning": "uncle"},
            {"hebrew": "דודה", "meaning": "aunt"},
            {"hebrew": "בן", "meaning": "son"},
            {"hebrew": "בת", "meaning": "daughter"},
        ],
    },
    {
        "title": "Food",
        "vocabulary": [
            {"hebrew": "לחם", "meaning": "bread"},
            {"hebrew": "מים", "meaning": "water"},
            {"hebrew": "חלב", "meaning": "milk"},
            {"hebrew": "ביצה", "meaning": "egg"},
            {"hebrew": "גבינה", "meaning": "cheese"},
            {"hebrew": "תפוח", "meaning": "apple"},
            {"hebrew": "בננה", "meaning": "banana"},
            {"hebrew": "עוף", "meaning": "chicken"},
            {"hebrew": "אורז", "meaning": "rice"},
            {"hebrew": "סלט", "meaning": "salad"},
        ],
    },
    {
        "title": "Animals",
        "vocabulary": [
            {"hebrew": "כלב", "meaning": "dog"},
            {"hebrew": "חתול", "meaning": "cat"},
            {"hebrew": "סוס", "meaning": "horse"},
            {"hebrew": "פרה", "meaning": "cow"},
            {"hebrew": "כבש", "meaning": "sheep"},
            {"hebrew": "אריה", "meaning": "lion"},
            {"hebrew": "דוב", "meaning": "bear"},
            {"hebrew": "ציפור", "meaning": "bird"},
            {"hebrew": "דג", "meaning": "fish"},
            {"hebrew": "נחש", "meaning": "snake"},
        ],
    },
    {
        "title": "Body Parts",
        "vocabulary": [
            {"hebrew": "ראש", "meaning": "head"},
            {"hebrew": "יד", "meaning": "hand"},
            {"hebrew": "רגל", "meaning": "leg"},
            {"hebrew": "עין", "meaning": "eye"},
            {"hebrew": "אוזן", "meaning": "ear"},
            {"hebrew": "פה", "meaning": "mouth"},
            {"hebrew": "אף", "meaning": "nose"},
            {"hebrew": "שיער", "meaning": "hair"},
            {"hebrew": "בטן", "meaning": "stomach"},
            {"hebrew": "גב", "meaning": "back"},
        ],
    },
    {
        "title": "Days of the Week",
        "vocabulary": [
            {"hebrew": "יום ראשון", "meaning": "Sunday"},
            {"hebrew": "יום שני", "meaning": "Monday"},
            {"hebrew": "יום שלישי", "meaning": "Tuesday"},
            {"hebrew": "יום רביעי", "meaning": "Wednesday"},
            {"hebrew": "יום חמישי", "meaning": "Thursday"},
            {"hebrew": "יום שישי", "meaning": "Friday"},
            {"hebrew": "שבת", "meaning": "Saturday"},
            {"hebrew": "שבוע", "meaning": "week"},
            {"hebrew": "היום", "meaning": "today"},
            {"hebrew": "מחר", "meaning": "tomorrow"},
        ],
    },
    {
        "title": "Time & Calendar",
        "vocabulary": [
            {"hebrew": "שעה", "meaning": "hour"},
            {"hebrew": "דקה", "meaning": "minute"},
            {"hebrew": "חודש", "meaning": "month"},
            {"hebrew": "שנה", "meaning": "year"},
            {"hebrew": "בוקר", "meaning": "morning"},
            {"hebrew": "צהריים", "meaning": "noon"},
            {"hebrew": "ערב", "meaning": "evening"},
            {"hebrew": "לילה", "meaning": "night"},
            {"hebrew": "עכשיו", "meaning": "now"},
            {"hebrew": "אתמול", "meaning": "yesterday"},
        ],
    },
    {
        "title": "Weather",
        "vocabulary": [
            {"hebrew": "שמש", "meaning": "sun"},
            {"hebrew": "גשם", "meaning": "rain"},
            {"hebrew": "רוח", "meaning": "wind"},
            {"hebrew": "שלג", "meaning": "snow"},
            {"hebrew": "ענן", "meaning": "cloud"},
            {"hebrew": "חם", "meaning": "hot"},
            {"hebrew": "קר", "meaning": "cold"},
            {"hebrew": "סוער", "meaning": "stormy"},
            {"hebrew": "בהיר", "meaning": "clear"},
            {"hebrew": "לח", "meaning": "humid"},
        ],
    },
    {
        "title": "Clothing",
        "vocabulary": [
            {"hebrew": "חולצה", "meaning": "shirt"},
            {"hebrew": "מכנסיים", "meaning": "pants"},
            {"hebrew": "שמלה", "meaning": "dress"},
            {"hebrew": "נעליים", "meaning": "shoes"},
            {"hebrew": "גרביים", "meaning": "socks"},
            {"hebrew": "מעיל", "meaning": "coat"},
            {"hebrew": "כובע", "meaning": "hat"},
            {"hebrew": "חגורה", "meaning": "belt"},
            {"hebrew": "חליפה", "meaning": "suit"},
            {"hebrew": "תיק", "meaning": "bag"},
        ],
    },
    {
        "title": "House & Home",
        "vocabulary": [
            {"hebrew": "בית", "meaning": "house"},
            {"hebrew": "חדר", "meaning": "room"},
            {"hebrew": "מטבח", "meaning": "kitchen"},
            {"hebrew": "חלון", "meaning": "window"},
            {"hebrew": "דלת", "meaning": "door"},
            {"hebrew": "שולחן", "meaning": "table"},
            {"hebrew": "כיסא", "meaning": "chair"},
            {"hebrew": "מיטה", "meaning": "bed"},
            {"hebrew": "אמבטיה", "meaning": "bathroom"},
            {"hebrew": "גינה", "meaning": "garden"},
        ],
    },
    {
        "title": "Transportation",
        "vocabulary": [
            {"hebrew": "מכונית", "meaning": "car"},
            {"hebrew": "אוטובוס", "meaning": "bus"},
            {"hebrew": "רכבת", "meaning": "train"},
            {"hebrew": "אופניים", "meaning": "bicycle"},
            {"hebrew": "מטוס", "meaning": "airplane"},
            {"hebrew": "ספינה", "meaning": "ship"},
            {"hebrew": "מונית", "meaning": "taxi"},
            {"hebrew": "כביש", "meaning": "road"},
            {"hebrew": "תחנה", "meaning": "station"},
            {"hebrew": "נמל תעופה", "meaning": "airport"},
        ],
    },
    {
        "title": "Occupations",
        "vocabulary": [
            {"hebrew": "מורה", "meaning": "teacher"},
            {"hebrew": "רופא", "meaning": "doctor"},
            {"hebrew": "עורך דין", "meaning": "lawyer"},
            {"hebrew": "שוטר", "meaning": "police officer"},
            {"hebrew": "טבח", "meaning": "cook"},
            {"hebrew": "נהג", "meaning": "driver"},
            {"hebrew": "מהנדס", "meaning": "engineer"},
            {"hebrew": "שחקן", "meaning": "actor"},
            {"hebrew": "סופר", "meaning": "writer"},
            {"hebrew": "חקלאי", "meaning": "farmer"},
        ],
    },
    {
        "title": "Emotions",
        "vocabulary": [
            {"hebrew": "שמח", "meaning": "happy"},
            {"hebrew": "עצוב", "meaning": "sad"},
            {"hebrew": "כועס", "meaning": "angry"},
            {"hebrew": "מפחד", "meaning": "scared"},
            {"hebrew": "מופתע", "meaning": "surprised"},
            {"hebrew": "עייף", "meaning": "tired"},
            {"hebrew": "רעב", "meaning": "hungry"},
            {"hebrew": "צמא", "meaning": "thirsty"},
            {"hebrew": "נרגש", "meaning": "excited"},
            {"hebrew": "משועמם", "meaning": "bored"},
        ],
    },
    {
        "title": "Nature",
        "vocabulary": [
            {"hebrew": "עץ", "meaning": "tree"},
            {"hebrew": "פרח", "meaning": "flower"},
            {"hebrew": "הר", "meaning": "mountain"},
            {"hebrew": "ים", "meaning": "sea"},
            {"hebrew": "נהר", "meaning": "river"},
            {"hebrew": "יער", "meaning": "forest"},
            {"hebrew": "אבן", "meaning": "rock"},
            {"hebrew": "חול", "meaning": "sand"},
            {"hebrew": "שמיים", "meaning": "sky"},
            {"hebrew": "כוכב", "meaning": "star"},
        ],
    },
    {
        "title": "School & Objects",
        "vocabulary": [
            {"hebrew": "ספר", "meaning": "book"},
            {"hebrew": "עט", "meaning": "pen"},
            {"hebrew": "עיפרון", "meaning": "pencil"},
            {"hebrew": "מחברת", "meaning": "notebook"},
            {"hebrew": "ילקוט", "meaning": "backpack"},
            {"hebrew": "לוח", "meaning": "board"},
            {"hebrew": "כיתה", "meaning": "classroom"},
            {"hebrew": "תלמיד", "meaning": "student"},
            {"hebrew": "בית ספר", "meaning": "school"},
            {"hebrew": "שיעור", "meaning": "lesson"},
        ],
    },
    {
        "title": "Directions & Places",
        "vocabulary": [
            {"hebrew": "ימין", "meaning": "right"},
            {"hebrew": "שמאל", "meaning": "left"},
            {"hebrew": "ישר", "meaning": "straight"},
            {"hebrew": "למעלה", "meaning": "up"},
            {"hebrew": "למטה", "meaning": "down"},
            {"hebrew": "קרוב", "meaning": "near"},
            {"hebrew": "רחוק", "meaning": "far"},
            {"hebrew": "עיר", "meaning": "city"},
            {"hebrew": "כפר", "meaning": "village"},
            {"hebrew": "רחוב", "meaning": "street"},
        ],
    },
    {
        "title": "Common Verbs",
        "vocabulary": [
            {"hebrew": "ללכת", "meaning": "to go"},
            {"hebrew": "לרוץ", "meaning": "to run"},
            {"hebrew": "לאכול", "meaning": "to eat"},
            {"hebrew": "לשתות", "meaning": "to drink"},
            {"hebrew": "לישון", "meaning": "to sleep"},
            {"hebrew": "לקרוא", "meaning": "to read"},
            {"hebrew": "לכתוב", "meaning": "to write"},
            {"hebrew": "לדבר", "meaning": "to speak"},
            {"hebrew": "לשמוע", "meaning": "to hear"},
            {"hebrew": "לראות", "meaning": "to see"},
        ],
    },
    {
        "title": "Common Adjectives",
        "vocabulary": [
            {"hebrew": "גדול", "meaning": "big"},
            {"hebrew": "קטן", "meaning": "small"},
            {"hebrew": "יפה", "meaning": "beautiful"},
            {"hebrew": "מכוער", "meaning": "ugly"},
            {"hebrew": "חדש", "meaning": "new"},
            {"hebrew": "ישן", "meaning": "old"},
            {"hebrew": "מהיר", "meaning": "fast"},
            {"hebrew": "איטי", "meaning": "slow"},
            {"hebrew": "קל", "meaning": "easy"},
            {"hebrew": "קשה", "meaning": "hard"},
        ],
    },
]
